In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('hotel_bookings.csv')

In [3]:
dataset

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July                        27   
3                    July                        27   
4                    July                        27   
...                   ...                       ...   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0   
1                               1                        0   
2                               1                        0   
3                               1                        0   
4                               1                        0   
...                           ...                      ...   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
0                          0       2  ...    No Deposit    NaN     NaN   
1                          0       2  ...    No Deposit    NaN     NaN   
2                          1       1  ...    No Deposit    NaN     NaN   
3                          1       1  ...    No Deposit  304.0     NaN   
4                          2       2  ...    No Deposit  240.0     NaN   
...                      ...     ...  ...           ...    ...     ...   
119385                     5       2  ...    No Deposit  394.0     NaN   
119386                     5       3  ...    No Deposit    9.0     NaN   
119387                     5       2  ...    No Deposit    9.0     NaN   
119388                     5       2  ...    No Deposit   89.0     NaN   
119389                     7       2  ...    No Deposit    9.0     NaN   

       days_in_waiting_list customer_type     adr  \
0                         0     Transient    0.00   
1                         0     Transient    0.00   
2                         0     Transient   75.00   
3                         0     Transient   75.00   
4                         0     Transient   98.00   
...                     ...           ...     ...   
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0   
1                                 0                          0   
2                                 0                          0   
3             

In [4]:
dataset.shape

(119390, 32)

Extracting independent variables from given data

In [5]:
x=dataset[['hotel','country','agent','company','customer_type']] #Extracting independent variables

In [6]:
x

hotel country  agent  company customer_type
0       Resort Hotel     PRT    NaN      NaN     Transient
1       Resort Hotel     PRT    NaN      NaN     Transient
2       Resort Hotel     GBR    NaN      NaN     Transient
3       Resort Hotel     GBR  304.0      NaN     Transient
4       Resort Hotel     GBR  240.0      NaN     Transient
...              ...     ...    ...      ...           ...
119385    City Hotel     BEL  394.0      NaN     Transient
119386    City Hotel     FRA    9.0      NaN     Transient
119387    City Hotel     DEU    9.0      NaN     Transient
119388    City Hotel     GBR   89.0      NaN     Transient
119389    City Hotel     DEU    9.0      NaN     Transient

[119390 rows x 5 columns]

In [7]:
x.values

array([['Resort Hotel', 'PRT', nan, nan, 'Transient'],
       ['Resort Hotel', 'PRT', nan, nan, 'Transient'],
       ['Resort Hotel', 'GBR', nan, nan, 'Transient'],
       ...,
       ['City Hotel', 'DEU', 9.0, nan, 'Transient'],
       ['City Hotel', 'GBR', 89.0, nan, 'Transient'],
       ['City Hotel', 'DEU', 9.0, nan, 'Transient']], dtype=object)

In [8]:
x=dataset.iloc[:,:-1].values

In [9]:
print(x)

[['Resort Hotel' 0 342 ... 0 0 'Check-Out']
 ['Resort Hotel' 0 737 ... 0 0 'Check-Out']
 ['Resort Hotel' 0 7 ... 0 0 'Check-Out']
 ...
 ['City Hotel' 0 34 ... 0 4 'Check-Out']
 ['City Hotel' 0 109 ... 0 0 'Check-Out']
 ['City Hotel' 0 205 ... 0 2 'Check-Out']]


In [10]:
y=dataset[['agent','company']]#extracting dependent variables..

In [11]:
y

agent  company
0         NaN      NaN
1         NaN      NaN
2         NaN      NaN
3       304.0      NaN
4       240.0      NaN
...       ...      ...
119385  394.0      NaN
119386    9.0      NaN
119387    9.0      NaN
119388   89.0      NaN
119389    9.0      NaN

[119390 rows x 2 columns]

In [12]:
y=dataset[['agent','company']].values

In [13]:
y

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       ...,
       [ 9., nan],
       [89., nan],
       [ 9., nan]])

missing values are represented as NaN

In [14]:
dataset.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [15]:
from sklearn.impute import SimpleImputer


In [16]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [17]:
imputer.fit(x[:,1:4])

SimpleImputer()

In [18]:
x[:,1:4]=imputer.transform(x[:,1:4])

In [19]:
print(x)

[['Resort Hotel' 0.0 342.0 ... 0 0 'Check-Out']
 ['Resort Hotel' 0.0 737.0 ... 0 0 'Check-Out']
 ['Resort Hotel' 0.0 7.0 ... 0 0 'Check-Out']
 ...
 ['City Hotel' 0.0 34.0 ... 0 4 'Check-Out']
 ['City Hotel' 0.0 109.0 ... 0 0 'Check-Out']
 ['City Hotel' 0.0 205.0 ... 0 2 'Check-Out']]


preprocessing -LabelEncoder


In [20]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [21]:
salary_class=pd.DataFrame({'Salary':[5000,75000,46000,9000,84000],
                          'Class':['Low','High','Medium','Low','High']})

In [22]:
lable_encode =LabelEncoder()

In [23]:
salary_class['Class'] = lable_encode.fit_transform(salary_class['Class'])


In [24]:
salary_class['Class']

0    1
1    0
2    2
3    1
4    0
Name: Class, dtype: int32

In [25]:
salary_class

Salary  Class
0    5000      1
1   75000      0
2   46000      2
3    9000      1
4   84000      0

preprocessing- OneHotEncoder

In [26]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


In [32]:
col_trans = ColumnTransformer([('encoder',OneHotEncoder(),[-1])],remainder='passthrough')


In [33]:
salary_class = np.array((col_trans.fit_transform(salary_class)))

In [34]:
print(salary_class)

[[0.0e+00 1.0e+00 0.0e+00 5.0e+03]
 [1.0e+00 0.0e+00 0.0e+00 7.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 4.6e+04]
 [0.0e+00 1.0e+00 0.0e+00 9.0e+03]
 [1.0e+00 0.0e+00 0.0e+00 8.4e+04]]
